# Generated by Django 5.2.4 on 2025-08-07 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn by Candidate')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter (max 1000 characters)', max_length=1000)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from employer')),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, help_text='Salary expectations (optional)', max_digits=10, null=True)),
                ('availability_date', models.DateField(blank=True, help_text='When can you start working?', null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='users.employeeprofile')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('in_person', 'In Person Interview'), ('technical', 'Technical Interview')], default='video', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes.')),
                ('location', models.CharField(blank=True, help_text='Physical address or video link.', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=15)),
                ('feedback', models.TextField(blank=True, help_text='Interview feedback and notes')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Interview score (1-10)', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job_applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn by Candidate')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn by Candidate')], max_length=20)),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='job_applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-changed_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Additional documents (CV, portfolio, certificates, etc.)', upload_to='application_documents/')),
                ('document_type', models.CharField(choices=[('CV', 'CV/Resume'), ('Portfolio', 'Portfolio'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Cover Letter', 'Cover Letter'), ('References', 'References'), ('Other', 'Other')], default='Other', help_text='Type of document', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Brief description of the document', max_length=200)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='job_applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('modality', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary range.', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary range.', max_digits=10, null=True)),
                ('experience_required', models.CharField(blank=True, help_text="Required years of experience (e.g. '2-5 years').", max_length=50)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField(blank=True, help_text='When applications close.', null=True)),
                ('state', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='users.employerprofile')),
                ('technologies', models.ManyToManyField(blank=True, related_name='vacancies', to='job_applications.technology')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='job_applications.vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('employee', 'vacancy')},
        ),
    ]
