# Generated by Django 5.2.4 on 2025-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='job_applications.technology'),
        ),
    ]
