# Generated by Django 5.2.4 on 2025-08-22 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_alter_vacancy_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='closing_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 22, 14, 51, 47, 111375, tzinfo=datetime.timezone.utc), help_text='When applications close.', null=True),
        ),
    ]
