# Generated by Django 5.2.4 on 2025-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0005_alter_vacancy_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='closing_date',
            field=models.DateTimeField(blank=True, help_text='When applications close.', null=True),
        ),
    ]
