# Generated by Django 5.2.4 on 2025-08-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0006_alter_vacancy_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='closing_date',
            field=models.DateField(blank=True, help_text='When applications close.', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
