# Generated by Django 5.2.4 on 2025-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0007_alter_vacancy_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='closing_date',
            field=models.DateTimeField(blank=True, help_text='When applications close.', null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
